lista_de_testes = [ (0, 'zero'),
                    (93, 'noventa e três'),
                    (100, 'cem'),
                    (101, 'cento e um'),
                    (148, 'cento e quarenta e oito'),
                    (167, 'cento e sessenta e sete'),
                    (572, 'quinhentos e setenta e dois'),
                    (581, 'quinhentos e oitenta e um'),
                    (844, 'oitocentos e quarenta e quatro'),
                    (1000, 'mil'),
                    (1001, 'mil e um'),
                    (1098, 'mil e noventa e oito'),
                    (1217, 'mil duzentos e dezessete'),
                    (1300, 'mil e trezentos'),
                    (2243, 'dois mil duzentos e quarenta e três'),
                    (3055, 'três mil e cinquenta e cinco'),
                    (4133, 'quatro mil cento e trinta e três'),
                    (6102, 'seis mil cento e dois'),
                    (8065, 'oito mil e sessenta e cinco'),
                    (10806, 'dez mil oitocentos e seis'),
                    (20377, 'vinte mil trezentos e setenta e sete'),
                    (37000, 'trinta e sete mil'),
                    (50034, 'cinquenta mil e trinta e quatro'),
                    (60279, 'sessenta mil duzentos e setenta e nove'),
                    (70034, 'setenta mil e trinta e quatro'),
                    (80364, 'oitenta mil trezentos e sessenta e quatro'),
                    (100001, 'cem mil e um'),
                    (145120, 'cento e quarenta e cinco mil cento e vinte'),
                    (200038, 'duzentos mil e trinta e oito'),
                    (200345, 'duzentos mil trezentos e quarenta e cinco'),
                    (300067, 'trezentos mil e sessenta e sete'),
                    (400800, 'quatrocentos mil e oitocentos'),
                    (401001, 'quatrocentos e um mil e um'),
                    (500090, 'quinhentos mil e noventa'),
                    (500603, 'quinhentos mil seiscentos e três'),
                    (600000, 'seiscentos mil'),
                    (600209, 'seiscentos mil duzentos e nove'),
                    (700501, 'setecentos mil quinhentos e um'),
                    (800209, 'oitocentos mil duzentos e nove'),
                    (803006, 'oitocentos e três mil e seis'),
                    (999999, 'novecentos e noventa e nove mil novecentos e noventa e nove')]

